# Generated by Django 2.0 on 2019-02-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
