# Generated by Django 2.0.13 on 2019-02-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20190226_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_time']},
        ),
    ]
